package/htop: fix uclibc build without wchar
Fix the following uclibc build failure without wchar raised since bump
to version 3.2.0 in commit b054353e59488713f841cd9ac9384b8a23f2e83a:

configure:5351: checking for /nvmedata/autobuild/instance-0/output-1/host/bin/i586-buildroot-linux-uclibc-gcc option to accept ISO C99
configure:5500: /nvmedata/autobuild/instance-0/output-1/host/bin/i586-buildroot-linux-uclibc-gcc  -c -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os -g1  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 conftest.c >&5
conftest.c:70:9: error: unknown type name 'wchar_t'
   70 |   const wchar_t *name;
      |         ^~~~~~~

[...]

configure: error: htop is written in C99. A newer compiler is required.

Fixes:
 - http://autobuild.buildroot.org/results/795bb4ae4f1a725c56353915c21fa784ca547c59

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>